"""Generate upload-ready Kaggle notebooks for TypePro sharding and training.

Generated notebooks never contain API credentials. Same-account jobs use the
Kaggle host identity; optional explicit credentials come from Kaggle Secrets.
"""
from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path
from textwrap import dedent


OWNER_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{1,49}$")
# Logical shards that exceeded Kaggle's runtime limit are committed as several
# versions of the same existing kernel. Each version owns one disjoint physical
# modulo partition, while unsplit shards retain their native index/10 coordinate.
SHARD_PART_COUNTS = {2: 2, 3: 3, 7: 2, 9: 3}
SHARD_PARTITIONS = {
    9: [(9, 30), (19, 30), (29, 90), (59, 90), (89, 90)],
}


def physical_partitions(shard_index: int) -> list[tuple[int, int]]:
    configured = SHARD_PARTITIONS.get(shard_index)
    if configured is not None:
        return list(configured)
    part_count = SHARD_PART_COUNTS.get(shard_index, 1)
    return [(shard_index + 10 * part_index, 10 * part_count)
            for part_index in range(part_count)]


if "__file__" in globals():
    ROOT = Path(__file__).resolve().parent
elif Path("/kaggle/working").is_dir():
    # When this source is pasted into a Kaggle/Jupyter cell, ``__file__`` does
    # not exist. Keep generated notebooks in the session output directory so
    # they can be downloaded or saved as notebook output.
    ROOT = Path("/kaggle/working/kaggle_notebooks")
else:
    ROOT = Path.cwd() / "kaggle_notebooks"


def markdown(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": dedent(source).strip() + "\n",
    }


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": dedent(source).strip() + "\n",
    }


def notebook(cells: list[dict], gpu: bool = False) -> dict:
    for index, cell in enumerate(cells):
        cell["id"] = f"cell-{index:03d}"
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"},
            "kaggle": {
                "accelerator": "nvidiaTeslaT4" if gpu else "none",
                "isGpuEnabled": gpu,
                "isInternetEnabled": True,
                "language": "python",
                "sourceType": "notebook",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def owner_test_notebook() -> dict:
    return notebook([
        markdown("""
        # Verify cross-account Kaggle Dataset ownership

        This creates a tiny **private** Dataset to verify which account owns an
        upload. It is safe to run from a notebook hosted by account B while
        authenticating with an API token belonging to account A.

        Recommended Secrets:

        - `KAGGLE_API_TOKEN`: current API token generated by the target owner.
        - `KAGGLE_DATASET_OWNER`: public Kaggle username that must own the Dataset.

        Legacy `KAGGLE_USERNAME` plus `KAGGLE_KEY` is also supported. The `key`
        inside a legacy `kaggle.json` is **not** a `KAGGLE_API_TOKEN`; configure
        it using the legacy pair instead. Never put a token directly in a cell
        or print it. Revoke a temporarily shared token after this test.
        """),
        code("""
        # Kaggle CLI is installed after selecting the authentication mode below.
        """),
        markdown("## Load the target owner's credentials from Kaggle Secrets"),
        code("""
        import json
        import os
        import re
        import subprocess
        import sys
        from pathlib import Path
        from kaggle_secrets import UserSecretsClient

        secrets = UserSecretsClient()

        def optional_secret(name):
            try:
                value = secrets.get_secret(name)
            except Exception:
                return None
            value = value.strip() if value else ""
            return value or None

        api_token = optional_secret("KAGGLE_API_TOKEN")
        legacy_username = optional_secret("KAGGLE_USERNAME")
        legacy_key = optional_secret("KAGGLE_KEY")
        dataset_owner = optional_secret("KAGGLE_DATASET_OWNER") or legacy_username

        print({
            "KAGGLE_API_TOKEN_present": bool(api_token),
            "KAGGLE_USERNAME_present": bool(legacy_username),
            "KAGGLE_KEY_present": bool(legacy_key),
            "secret_values_printed": False,
        })
        if bool(legacy_username) != bool(legacy_key):
            raise RuntimeError(
                "Legacy authentication is incomplete: KAGGLE_USERNAME and "
                "KAGGLE_KEY must both be present"
            )

        if not dataset_owner:
            raise RuntimeError(
                "Add KAGGLE_DATASET_OWNER (recommended with KAGGLE_API_TOKEN) "
                "or KAGGLE_USERNAME to Kaggle Secrets"
            )
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{1,49}", dataset_owner):
            raise ValueError(f"Invalid KAGGLE_DATASET_OWNER: {dataset_owner!r}")

        # Isolate the CLI from any OAuth/config file belonging to the account
        # that hosts this notebook. Only the explicitly supplied Secret below
        # is allowed to authenticate this test.
        auth_config_dir = Path("/kaggle/working/typepro_owner_test_auth")
        auth_config_dir.mkdir(parents=True, exist_ok=True)
        os.environ["KAGGLE_CONFIG_DIR"] = str(auth_config_dir)

        # A complete legacy pair is explicit and takes precedence. This is
        # important in a cross-account Kaggle notebook because the hosting
        # account may also expose its own access token/OAuth credentials.
        if legacy_username and legacy_key:
            if dataset_owner.casefold() != legacy_username.casefold():
                raise RuntimeError(
                    "With legacy credentials, KAGGLE_DATASET_OWNER must equal KAGGLE_USERNAME"
                )
            os.environ.pop("KAGGLE_API_TOKEN", None)
            os.environ["KAGGLE_USERNAME"] = legacy_username
            os.environ["KAGGLE_KEY"] = legacy_key
            auth_mode = "legacy KAGGLE_USERNAME/KAGGLE_KEY"
        elif api_token:
            # Explicitly prefer the supplied target-owner token over any
            # credentials inherited from the notebook-hosting account.
            os.environ["KAGGLE_API_TOKEN"] = api_token
            os.environ.pop("KAGGLE_USERNAME", None)
            os.environ.pop("KAGGLE_KEY", None)
            auth_mode = "KAGGLE_API_TOKEN"
        else:
            raise RuntimeError(
                "Add either KAGGLE_API_TOKEN, or both KAGGLE_USERNAME and KAGGLE_KEY"
            )

        if auth_mode == "legacy KAGGLE_USERNAME/KAGGLE_KEY":
            # Kaggle CLI >=1.8 can consume the notebook-hosting account's
            # automatically provided access token before checking the explicit
            # legacy pair. Version 1.7.4.2 predates that authentication path.
            subprocess.run(
                [
                    sys.executable, "-m", "pip", "install", "-q",
                    "--force-reinstall", "kaggle==1.7.4.2",
                ],
                check=True,
            )
        else:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "-q", "-U", "kaggle"],
                check=True,
            )

        # Import Kaggle in a fresh process. Importing authenticates immediately,
        # so this reveals both the effective account and whether the supplied
        # Secret was accepted instead of silently falling back to host OAuth.
        identity_code = "\\n".join([
            "import json",
            "import kaggle",
            "api = kaggle.api",
            'values = getattr(api, "config_values", {})',
            'username = values.get("username")',
            'method = values.get("auth_method") or "LEGACY_API_KEY"',
            'print("TYPEPRO_KAGGLE_IDENTITY=" + json.dumps({',
            '    "username": username,',
            '    "auth_method": method,',
            '}))',
        ])
        identity_result = subprocess.run(
            [sys.executable, "-c", identity_code],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        identity_prefix = "TYPEPRO_KAGGLE_IDENTITY="
        identity_line = next(
            (
                line for line in (identity_result.stdout or "").splitlines()
                if line.startswith(identity_prefix)
            ),
            None,
        )
        if identity_result.returncode or identity_line is None:
            raise RuntimeError(
                "Kaggle authentication preflight failed. If you copied the key from "
                "kaggle.json, use KAGGLE_USERNAME + KAGGLE_KEY instead of "
                f"KAGGLE_API_TOKEN. CLI output: {identity_result.stdout}"
            )
        identity = json.loads(identity_line[len(identity_prefix):])
        authenticated_username = (identity.get("username") or "").strip()
        authenticated_method = (identity.get("auth_method") or "").strip()
        expected_method = (
            "LEGACY_API_KEY"
            if auth_mode == "legacy KAGGLE_USERNAME/KAGGLE_KEY"
            else "ACCESS_TOKEN"
        )
        if authenticated_username.casefold() != dataset_owner.casefold():
            raise RuntimeError(
                f"Credential authenticated as {authenticated_username!r}, but the requested "
                f"Dataset owner is {dataset_owner!r}. Use a credential generated by "
                "the requested owner account."
            )
        if authenticated_method != expected_method:
            raise RuntimeError(
                f"The supplied {auth_mode} was not accepted; Kaggle CLI used "
                f"{authenticated_method!r} instead. If this is a key from kaggle.json, "
                "remove KAGGLE_API_TOKEN and set KAGGLE_USERNAME + KAGGLE_KEY."
            )

        print({
            "requested_dataset_owner": dataset_owner,
            "authentication_mode": auth_mode,
            "authenticated_username": authenticated_username,
            "authenticated_method": authenticated_method,
            "secrets_printed": False,
        })
        """),
        markdown("## Create and validate a tiny private Dataset"),
        code("""
        import json
        import subprocess
        import time
        import uuid
        from datetime import datetime, timezone
        from pathlib import Path

        def run_capture(command):
            print("+", " ".join(map(str, command)), flush=True)
            result = subprocess.run(
                [str(value) for value in command],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            )
            if result.stdout:
                print(result.stdout.rstrip(), flush=True)
            return result

        now = datetime.now(timezone.utc)
        suffix = f"{now:%Y%m%d-%H%M%S}-{uuid.uuid4().hex[:6]}"
        dataset_slug = f"typepro-owner-test-{suffix}"
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]{2,49}", dataset_slug):
            raise RuntimeError(f"Generated invalid Dataset slug: {dataset_slug}")
        dataset_id = f"{dataset_owner}/{dataset_slug}"
        title = f"TypePro owner test {now:%Y%m%d %H%M%S}"
        if not 6 <= len(title) <= 50:
            raise RuntimeError(f"Generated invalid Dataset title: {title!r}")

        payload_dir = Path("/kaggle/working/typepro_owner_test_payload")
        payload_dir.mkdir(parents=True, exist_ok=True)
        record = {
            "purpose": "Verify cross-account Kaggle Dataset ownership",
            "requested_owner": dataset_owner,
            "created_at": now.isoformat(),
            "dataset_id": dataset_id,
        }
        (payload_dir / "owner_test.json").write_text(
            json.dumps(record, indent=2), encoding="utf-8"
        )
        metadata = {
            "title": title,
            "id": dataset_id,
            "licenses": [{"name": "CC-BY-4.0"}],
        }
        metadata_path = payload_dir / "dataset-metadata.json"
        metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        if json.loads(metadata_path.read_text(encoding="utf-8")) != metadata:
            raise RuntimeError("dataset-metadata.json verification failed")

        version_result = run_capture(["kaggle", "--version"])
        if version_result.returncode:
            raise RuntimeError("Kaggle CLI is unavailable")
        create_result = run_capture([
            "kaggle", "datasets", "create",
            "-p", payload_dir,
            "--dir-mode", "skip",
        ])
        create_text = create_result.stdout or ""
        create_lower = create_text.casefold()
        create_succeeded = (
            "dataset is being created" in create_lower
            and "dataset creation error:" not in create_lower
        )
        # Kaggle CLI 2.2.4 prints a server-side Dataset creation error but can
        # still exit with code 0. Never poll a slug that was not registered.
        if create_result.returncode or not create_succeeded:
            raise RuntimeError(
                f"Dataset registration failed for {dataset_id}. Kaggle may have uploaded "
                "the blob without creating the Dataset. Verify Dataset write permission "
                f"for the authenticated owner. CLI output: {create_text}"
            )

        # The legacy status endpoint can return 403 even immediately after a
        # successful create. Listing the uploaded file is a stronger end-to-end
        # verification and works with legacy credentials.
        deadline = time.monotonic() + 600
        final_status = None
        last_files_output = ""
        while time.monotonic() < deadline:
            files_result = run_capture([
                "kaggle", "datasets", "files", dataset_id, "--page-size", "10"
            ])
            last_files_output = files_result.stdout or ""
            if files_result.returncode == 0 and "owner_test.json" in last_files_output:
                final_status = "ready; owner_test.json is listable"
                break
            files_text = last_files_output.casefold()
            transient = any(
                marker in files_text
                for marker in ("403", "404", "forbidden", "not found", "could not find")
            )
            if files_result.returncode and not transient:
                raise RuntimeError(f"Cannot list Dataset files: {last_files_output}")
            print("Dataset files are not ready yet; checking again in 10 seconds", flush=True)
            time.sleep(10)
        if final_status is None:
            raise TimeoutError(
                f"Dataset file did not become listable within 600 seconds: {dataset_id}; "
                f"last output: {last_files_output}"
            )

        dataset_url = f"https://www.kaggle.com/datasets/{dataset_id}"
        print(json.dumps({
            "verified": True,
            "owner": dataset_owner,
            "dataset_id": dataset_id,
            "dataset_url": dataset_url,
            "status": final_status,
        }, indent=2, ensure_ascii=False))
        """),
        markdown("""
        A result with `"verified": true` proves that Kaggle accepted the
        requested `owner/slug`, finished processing it, and exposes the uploaded
        test file. Open `dataset_url` while signed into the target owner account.
        """),
    ])


def shard_notebook(
    index: int,
    count: int,
    repository: str,
    branch: str,
    *,
    assigned_shards: list[int] | None = None,
    expected_dataset_owner: str | None = None,
    public_dataset: bool = False,
) -> dict:
    assigned_shards = list(assigned_shards or [index])
    if not assigned_shards or len(set(assigned_shards)) != len(assigned_shards):
        raise ValueError(f"assigned_shards must be non-empty and unique: {assigned_shards}")
    if any(shard < 0 or shard >= count for shard in assigned_shards):
        raise ValueError(f"assigned_shards must be within 0..{count - 1}: {assigned_shards}")
    if index not in assigned_shards:
        raise ValueError(f"initial shard {index} is not assigned to this notebook")
    if assigned_shards != [index]:
        raise ValueError(
            "The ten-shard workflow requires one standalone notebook per shard"
        )
    expected_dataset_owner = (expected_dataset_owner or "").strip()
    if not OWNER_RE.fullmatch(expected_dataset_owner):
        raise ValueError(
            f"expected_dataset_owner must be a valid Kaggle username: "
            f"{expected_dataset_owner!r}"
        )
    if not isinstance(public_dataset, bool):
        raise TypeError("public_dataset must be boolean")
    title = f"TypePro Python shard {index:02d} of {count}"
    result = notebook([
        markdown(f"""
        # {title}

        Settings required: **Internet ON**, accelerator **None/CPU**. This
        standalone notebook is permanently assigned shard `{index:02d}` and
        publishes `typepro-build-shard-{index:02d}` as a
        `{("public" if public_dataset else "private")}` Dataset under
        `{expected_dataset_owner or 'the authenticated publish owner'}`.

        The notebook uses its same-account Kaggle host identity by default.
        Optional target-owner Secrets `TYPEPRO_PUBLISH_USERNAME` and
        `TYPEPRO_PUBLISH_KEY` (or legacy `KAGGLE_USERNAME` and `KAGGLE_KEY`)
        override it. The notebook refuses to run when the effective publish
        owner is not the expected owner.
        """),
        code(f"""
        # This standalone notebook permanently builds exactly one shard.
        ASSIGNED_SHARDS = {assigned_shards!r}
        SHARD_INDEX = {index}
        SHARD_COUNT = {count}
        EXPECTED_DATASET_OWNER = {expected_dataset_owner!r}
        PUBLISH_PUBLIC = {public_dataset!r}
        REPOSITORY = {repository!r}
        BRANCH = {branch!r}
        SEED = 13
        TEST_PROJECTS = 100
        VALIDATION_PROJECT_RATIO = 0.10
        SLICE_LOG_EVERY = 50
        # Trace every annotation so the parent hard-kill timer is armed for
        # each one; a pathological slice in native code cannot stall a shard.
        SLICE_TRACE_EVERY = 1
        # Bound every annotation so one pathological slice cannot stall a shard.
        SLICE_ANNOTATION_TIMEOUT_SECONDS = 120
        # Bound work that happens before annotation export as well.
        PACKAGE_DOWNLOAD_TIMEOUT_SECONDS = 900
        KB_PHASE_TIMEOUT_SECONDS = 1800
        PROJECT_ANALYSIS_TIMEOUT_SECONDS = 300
        # Kill an exporter stuck building a project index after 30 minutes.
        SLICE_INDEX_TIMEOUT_SECONDS = 1800
        # Kill a stuck git clone after 15 minutes.
        CLONE_TIMEOUT_SECONDS = 900
        # This rerun keeps built-in annotations and adds function returns.
        INCLUDE_BUILTINS = True
        INCLUDE_RETURNS = True
        RETRIEVAL_SCHEMA_VERSION = "typepro-project-kb-top10-generative-v2"

        from pathlib import Path

        REPO_DIR = Path("/kaggle/working/TypePro")
        WORK_DIR = Path(f"/kaggle/working/typepro_build_shard_{{SHARD_INDEX:02d}}")
        PUBLISH_DIR = Path(f"/kaggle/working/publish_shard_{{SHARD_INDEX:02d}}")
        if SHARD_INDEX not in ASSIGNED_SHARDS:
            raise RuntimeError(
                f"Shard {{SHARD_INDEX}} is not assigned to this notebook: {{ASSIGNED_SHARDS}}"
            )
        print({{
            "assigned_shards": ASSIGNED_SHARDS,
            "shard_index": SHARD_INDEX,
            "shard_count": SHARD_COUNT,
            "expected_dataset_owner": EXPECTED_DATASET_OWNER or None,
            "publish_public": PUBLISH_PUBLIC,
            "work_dir": str(WORK_DIR),
        }})
        """),
        markdown("""
        ## Authenticate safely

        Optional values are read from Kaggle Secrets and are never printed. If
        supplied, a separate config directory prevents the notebook host's
        automatic credential from overriding the explicit credential.
        """),
        code("""
        import json
        import os
        import re
        from kaggle_secrets import UserSecretsClient

        secrets = UserSecretsClient()

        def optional_secret(name):
            try:
                value = secrets.get_secret(name)
            except Exception:
                return None
            value = value.strip() if value else ""
            return value or None

        target_username = optional_secret("TYPEPRO_PUBLISH_USERNAME")
        target_key = optional_secret("TYPEPRO_PUBLISH_KEY")
        legacy_username = optional_secret("KAGGLE_USERNAME")
        legacy_key = optional_secret("KAGGLE_KEY")
        if bool(target_username) != bool(target_key):
            raise RuntimeError(
                "TYPEPRO_PUBLISH_USERNAME and TYPEPRO_PUBLISH_KEY must both be present"
            )
        if bool(legacy_username) != bool(legacy_key):
            raise RuntimeError("KAGGLE_USERNAME and KAGGLE_KEY must both be present")
        publish_username = target_username or legacy_username
        publish_key = target_key or legacy_key
        use_explicit_credential = bool(publish_username and publish_key)
        if not use_explicit_credential:
            # The notebook is pushed to the same account that owns its shard
            # Datasets. Kaggle supplies that host identity automatically, so
            # Secrets are optional for this normal same-account path.
            publish_username = EXPECTED_DATASET_OWNER
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{1,49}", publish_username):
            raise ValueError(f"Invalid publish username: {publish_username!r}")
        if (
            EXPECTED_DATASET_OWNER
            and publish_username.casefold() != EXPECTED_DATASET_OWNER.casefold()
        ):
            raise RuntimeError(
                f"Publish credential belongs to {publish_username!r}; all TypePro "
                f"Datasets must belong to {EXPECTED_DATASET_OWNER!r}"
            )

        if use_explicit_credential:
            auth_config_dir = Path("/kaggle/working/typepro_publish_auth")
            auth_config_dir.mkdir(parents=True, exist_ok=True)
            os.environ["KAGGLE_CONFIG_DIR"] = str(auth_config_dir)
            os.environ["KAGGLE_USERNAME"] = publish_username
            os.environ["KAGGLE_KEY"] = publish_key
            os.environ.pop("KAGGLE_API_TOKEN", None)
            authentication_source = "explicit Kaggle Secret"
        else:
            authentication_source = "Kaggle notebook host"
        # publish_shard.py validates the requested Dataset owner against this
        # non-secret value. Keep the host access token untouched.
        os.environ["KAGGLE_USERNAME"] = publish_username
        os.environ["PYTHONUNBUFFERED"] = "1"
        print({
            "publish_owner": publish_username,
            "expected_owner": EXPECTED_DATASET_OWNER or publish_username,
            "authentication_source": authentication_source,
            "credentials_printed": False,
        })
        """),
        markdown("## Clone TypePro and install builder dependencies"),
        code("""
        import shutil
        import subprocess
        import sys

        def run(command, cwd=None):
            print("+", " ".join(map(str, command)), flush=True)
            subprocess.run([str(value) for value in command], cwd=cwd, check=True)

        if not REPO_DIR.exists():
            run(["git", "clone", "--branch", BRANCH, "--single-branch", REPOSITORY, REPO_DIR])
        else:
            print("Using existing repository:", REPO_DIR)

        PIPELINE_DIR = REPO_DIR / "codet5p_type_retrieval"
        run([sys.executable, "-m", "pip", "install", "-q", "-U", "-r", PIPELINE_DIR / "requirements-build.txt"])
        if use_explicit_credential:
            # This release always honors the explicit legacy username/key pair.
            run([sys.executable, "-m", "pip", "install", "-q", "--force-reinstall", "kaggle==1.7.4.2"])
        else:
            # Current Kaggle releases understand the notebook host's automatic
            # access token. No credential value is copied into this notebook.
            run([sys.executable, "-m", "pip", "install", "-q", "-U", "kaggle"])

        identity_code = "\\n".join([
            "import json",
            "import kaggle",
            "values = getattr(kaggle.api, 'config_values', {})",
            "print('TYPEPRO_KAGGLE_IDENTITY=' + json.dumps({",
            "    'username': values.get('username'),",
            "    'auth_method': values.get('auth_method') or 'LEGACY_API_KEY',",
            "}))",
        ])
        identity_result = subprocess.run(
            [sys.executable, "-c", identity_code],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        identity_prefix = "TYPEPRO_KAGGLE_IDENTITY="
        identity_line = next(
            (
                line for line in (identity_result.stdout or "").splitlines()
                if line.startswith(identity_prefix)
            ),
            None,
        )
        if identity_result.returncode or identity_line is None:
            raise RuntimeError(
                f"Kaggle publish authentication failed: {identity_result.stdout}"
            )
        identity = json.loads(identity_line[len(identity_prefix):])
        authenticated_username = (identity.get("username") or "").strip()
        if authenticated_username.casefold() != publish_username.casefold():
            raise RuntimeError(
                f"Kaggle authenticated as {authenticated_username!r}, expected "
                f"publish owner {publish_username!r}"
            )
        print({
            "authenticated_publish_owner": authenticated_username,
            "authentication_method": identity.get("auth_method"),
        })
        """),
        markdown("""
        ## Optional automatic resume

        If the private shard dataset already exists, its archive is downloaded
        and restored before slicing. A missing dataset simply means this is the
        first run.
        """),
        code("""
        import json
        import zipfile

        dataset_id = f"{publish_username}/typepro-build-shard-{SHARD_INDEX:02d}"
        resume_dir = Path(f"/kaggle/working/resume_shard_{SHARD_INDEX:02d}")
        resume_dir.mkdir(parents=True, exist_ok=True)
        probe = subprocess.run(
            ["kaggle", "datasets", "files", dataset_id],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        has_work = (
            (WORK_DIR / "metadata" / "split_manifest.json").exists()
            or any((WORK_DIR / "raw_slices").glob("*.jsonl"))
            or any((WORK_DIR / "project_status").glob("*.json"))
        )
        if probe.returncode == 0 and not has_work:
            run(["kaggle", "datasets", "download", "-d", dataset_id, "-p", resume_dir, "--unzip"])
            markers = list(resume_dir.rglob("shard_manifest.json"))
            if not markers:
                archives = list(resume_dir.rglob("typepro_build_shard_*.zip"))
                if len(archives) != 1:
                    raise RuntimeError(
                        f"Expected one shard directory or archive, found markers={markers}, archives={archives}"
                    )
                with zipfile.ZipFile(archives[0]) as bundle:
                    bundle.extractall(resume_dir)
                markers = list(resume_dir.rglob("shard_manifest.json"))
            if len(markers) != 1:
                raise RuntimeError(f"Cannot uniquely locate restored shard: {markers}")
            source_build = markers[0].parent
            restored_manifest = json.loads(markers[0].read_text(encoding="utf-8"))
            restored_runtime_path = source_build / "runtime_manifest.json"
            restored_runtime = (
                json.loads(restored_runtime_path.read_text(encoding="utf-8"))
                if restored_runtime_path.exists() else {}
            )
            if (
                restored_manifest.get("shard_index") != SHARD_INDEX
                or restored_manifest.get("shard_count") != SHARD_COUNT
                or restored_runtime.get("retrieval_schema_version")
                != RETRIEVAL_SCHEMA_VERSION
            ):
                print(
                    "Ignoring an incompatible previous shard Dataset; starting fresh:",
                    {
                        "manifest": restored_manifest,
                        "retrieval_schema_version": restored_runtime.get(
                            "retrieval_schema_version"
                        ),
                        "expected_retrieval_schema_version": RETRIEVAL_SCHEMA_VERSION,
                    },
                )
            else:
                shutil.copytree(source_build, WORK_DIR, dirs_exist_ok=True)
                print("Restored previous shard state:", WORK_DIR)
        else:
            print("Starting new shard or using current working state")
        """),
        markdown("## Download metadata and create the deterministic project split"),
        code("""
        prepare = PIPELINE_DIR / "prepare_dataset.py"
        common = [
            "--typepro-root", REPO_DIR,
            "--work-dir", WORK_DIR,
            "--split-profile", "paper_project",
            "--test-projects", TEST_PROJECTS,
            "--validation-project-ratio", VALIDATION_PROJECT_RATIO,
            "--seed", SEED,
            "--preview-samples", 1,
            "--preview-max-chars", 1200,
        ]
        if INCLUDE_BUILTINS:
            common.append("--include-builtins")
        if INCLUDE_RETURNS:
            common.append("--include-returns")
        run([sys.executable, "-u", prepare, "--stage", "metadata", *common])
        """),
        markdown("## Clone repositories and build interprocedural slices"),
        code("""
        run([
            sys.executable, "-u", prepare,
            "--stage", "slice",
            *common,
            "--shard-count", SHARD_COUNT,
            "--shard-index", SHARD_INDEX,
            "--slice-log-every", SLICE_LOG_EVERY,
            "--slice-trace-every", SLICE_TRACE_EVERY,
            "--slice-annotation-timeout-seconds", SLICE_ANNOTATION_TIMEOUT_SECONDS,
            "--package-download-timeout-seconds", PACKAGE_DOWNLOAD_TIMEOUT_SECONDS,
            "--kb-phase-timeout-seconds", KB_PHASE_TIMEOUT_SECONDS,
            "--project-analysis-timeout-seconds", PROJECT_ANALYSIS_TIMEOUT_SECONDS,
            "--slice-index-timeout-seconds", SLICE_INDEX_TIMEOUT_SECONDS,
            "--clone-timeout-seconds", CLONE_TIMEOUT_SECONDS,
            "--retrieval-schema-version", RETRIEVAL_SCHEMA_VERSION,
            "--build-import-kb",
            "--download-missing-imports",
            "--kb-max-files-per-package", 3000,
        ])
        """),
        markdown("## Verify that this shard attempted every assigned project"),
        code("""
        import json
        sys.path.insert(0, str(PIPELINE_DIR))
        from prepare_dataset import project_from_row, read_json, stable_number

        projects = set()
        for split in ("train", "validation", "test"):
            for row in read_json(WORK_DIR / "metadata" / f"{split}.json"):
                projects.add(project_from_row(row))
        selected = {
            project for project in projects
            if stable_number(project, SEED + 4) % SHARD_COUNT == SHARD_INDEX
        }
        statuses = []
        for path in (WORK_DIR / "project_status").glob("*.json"):
            statuses.append(json.loads(path.read_text(encoding="utf-8")))
        attempted = {item.get("project") for item in statuses}
        missing = sorted(selected - attempted)
        summary = {
            "shard_index": SHARD_INDEX,
            "shard_count": SHARD_COUNT,
            "selected_projects": len(selected),
            "attempted_projects": len(selected & attempted),
            "successful_projects": sum(item.get("project") in selected and "error" not in item for item in statuses),
            "failed_projects": sum(item.get("project") in selected and "error" in item for item in statuses),
            "exported_slices": sum(int(item.get("exported", 0)) for item in statuses if item.get("project") in selected),
            "missing_projects": missing,
        }
        print(json.dumps(summary, indent=2, ensure_ascii=False))
        (WORK_DIR / "shard_manifest.json").write_text(
            json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        if missing:
            raise RuntimeError(f"Shard is incomplete: {len(missing)} projects missing")
        """),
        markdown(
            "## Package and publish this shard as a "
            + ("public" if public_dataset else "private")
            + " Kaggle Dataset"
        ),
        code("""
        publish_command = [
            sys.executable, "-u", PIPELINE_DIR / "publish_shard.py",
            "--work-dir", WORK_DIR,
            "--payload-dir", PUBLISH_DIR,
            "--dataset-id", dataset_id,
            "--title", f"TypePro Python shard {SHARD_INDEX:02d} of {SHARD_COUNT}",
            "--message", f"Completed TypePro shard {SHARD_INDEX:02d} of {SHARD_COUNT}",
            "--expected-shard-index", SHARD_INDEX,
            "--expected-shard-count", SHARD_COUNT,
        ]
        if PUBLISH_PUBLIC:
            publish_command.append("--public")
        run(publish_command)
        """),
    ])
    result["cells"][1]["metadata"] = {"tags": ["typepro-shard-config"]}
    result["metadata"]["typepro"] = {
        "assigned_shards": assigned_shards,
        "initial_shard_index": index,
        "expected_dataset_owner": expected_dataset_owner or None,
        "public_dataset": public_dataset,
    }
    return result


def canonical_merge_datasets(shard_accounts: list[dict]) -> list[dict]:
    datasets = []
    for account in shard_accounts:
        for index in account["assigned_shards"]:
            partitions = physical_partitions(index)
            for part_index, (physical_index, physical_count) in enumerate(partitions):
                datasets.append({
                    "dataset_id": (
                        f"{account['dataset_owner']}/"
                        f"typepro-build-shard-{physical_index:02d}"
                    ),
                    "logical_shard_index": index,
                    "part_index": part_index,
                    "part_count": len(partitions),
                    "shard_index": physical_index,
                    "shard_count": physical_count,
                    "public_dataset": bool(account["public_dataset"]),
                })
    return datasets


def validate_merge_datasets(
    datasets: list[dict],
    count: int,
    expected_dataset_owner: str,
) -> list[dict]:
    normalized = []
    seen_ids = set()
    for item in datasets:
        dataset_id = item.get("dataset_id")
        logical_index = item.get("logical_shard_index")
        shard_index = item.get("shard_index")
        shard_count = item.get("shard_count")
        public_dataset = item.get("public_dataset")
        if not isinstance(dataset_id, str) or dataset_id.count("/") != 1:
            raise ValueError(f"Invalid merge Dataset id: {dataset_id!r}")
        owner, slug = dataset_id.split("/", 1)
        if (
            not OWNER_RE.fullmatch(owner)
            or not isinstance(shard_index, int)
            or slug != f"typepro-build-shard-{shard_index:02d}"
        ):
            raise ValueError(f"Dataset id does not match its physical shard: {item!r}")
        if dataset_id.casefold() in seen_ids:
            raise ValueError(f"Duplicate merge Dataset: {dataset_id}")
        if not isinstance(logical_index, int) or logical_index not in range(count):
            raise ValueError(f"Invalid logical shard index: {item!r}")
        if (
            not isinstance(shard_count, int)
            or shard_count <= 0
            or shard_index not in range(shard_count)
            or shard_count % count
        ):
            raise ValueError(f"Invalid physical shard coordinates: {item!r}")
        if shard_index % count != logical_index:
            raise ValueError(f"Physical shard does not belong to logical shard: {item!r}")
        if not isinstance(public_dataset, bool):
            raise ValueError(f"public_dataset must be boolean: {item!r}")
        should_be_public = owner.casefold() != expected_dataset_owner.casefold()
        if public_dataset != should_be_public:
            raise ValueError(
                "Datasets outside the final owner must be public and final-owner "
                f"Datasets must be private: {item!r}"
            )
        seen_ids.add(dataset_id.casefold())
        normalized.append(dict(item))

    modulus = math.lcm(*(item["shard_count"] for item in normalized))
    coverage = [None] * modulus
    for item in normalized:
        for residue in range(item["shard_index"], modulus, item["shard_count"]):
            if coverage[residue] is not None:
                raise ValueError(
                    f"Overlapping merge partitions at residue {residue}/{modulus}: "
                    f"{coverage[residue]} and {item['dataset_id']}"
                )
            coverage[residue] = item["dataset_id"]
    missing = [residue for residue, dataset_id in enumerate(coverage) if dataset_id is None]
    if missing:
        raise ValueError(f"Merge partitions do not cover all logical shards: {missing}")
    return normalized


def recovery_notebook(
    index: int,
    count: int,
    repository: str,
    branch: str,
    *,
    expected_dataset_owner: str,
    public_dataset: bool,
    source_kernel: str,
) -> dict:
    """Create a publish-only notebook backed by one saved kernel version."""
    if not 0 <= index < count:
        raise ValueError(f"Shard index must be within 0..{count - 1}: {index}")
    if not OWNER_RE.fullmatch(expected_dataset_owner):
        raise ValueError(f"Invalid Dataset owner: {expected_dataset_owner!r}")
    if not re.fullmatch(r"[A-Za-z0-9_-]+/[A-Za-z0-9_-]+/\d+", source_kernel):
        raise ValueError(f"Invalid versioned source kernel: {source_kernel!r}")
    return notebook([
        markdown(f"""
        # Recover completed TypePro shard {index:02d}

        This notebook does not rebuild projects. It downloads the exact saved
        output of `{source_kernel}` directly inside Kaggle, validates its
        manifest, repackages it, and publishes
        `{expected_dataset_owner}/typepro-build-shard-{index:02d}`.
        """),
        code(f"""
        SHARD_INDEX = {index}
        SHARD_COUNT = {count}
        EXPECTED_DATASET_OWNER = {expected_dataset_owner!r}
        PUBLISH_PUBLIC = {public_dataset!r}
        SOURCE_KERNEL = {source_kernel!r}
        REPOSITORY = {repository!r}
        BRANCH = {branch!r}

        import json
        import os
        import re
        import shutil
        import subprocess
        import sys
        import zipfile
        from pathlib import Path, PurePosixPath

        os.environ["KAGGLE_USERNAME"] = EXPECTED_DATASET_OWNER
        os.environ["PYTHONUNBUFFERED"] = "1"

        def run(command, cwd=None):
            print("+", " ".join(map(str, command)), flush=True)
            subprocess.run([str(value) for value in command], cwd=cwd, check=True)

        print({{
            "shard_index": SHARD_INDEX,
            "shard_count": SHARD_COUNT,
            "dataset_owner": EXPECTED_DATASET_OWNER,
            "public_dataset": PUBLISH_PUBLIC,
            "source_kernel": SOURCE_KERNEL,
            "credentials_printed": False,
        }})
        """),
        markdown("## Verify the automatic host identity and clone the fixed publisher"),
        code("""
        run([sys.executable, "-m", "pip", "install", "-q", "-U", "kaggle"])
        identity_code = "\\n".join([
            "import json",
            "import kaggle",
            "values = getattr(kaggle.api, 'config_values', {})",
            "print('TYPEPRO_KAGGLE_IDENTITY=' + json.dumps({",
            "    'username': values.get('username'),",
            "    'auth_method': values.get('auth_method'),",
            "}))",
        ])
        identity_result = subprocess.run(
            [sys.executable, "-c", identity_code],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        identity_prefix = "TYPEPRO_KAGGLE_IDENTITY="
        identity_line = next(
            (
                line for line in (identity_result.stdout or "").splitlines()
                if line.startswith(identity_prefix)
            ),
            None,
        )
        if identity_result.returncode or identity_line is None:
            raise RuntimeError(
                f"Kaggle host authentication failed: {identity_result.stdout}"
            )
        identity = json.loads(identity_line[len(identity_prefix):])
        authenticated_username = (identity.get("username") or "").strip()
        if authenticated_username.casefold() != EXPECTED_DATASET_OWNER.casefold():
            raise RuntimeError(
                f"Kaggle authenticated as {authenticated_username!r}, expected "
                f"{EXPECTED_DATASET_OWNER!r}"
            )
        print({
            "authenticated_owner": authenticated_username,
            "authentication_method": identity.get("auth_method"),
        })

        REPO_DIR = Path("/kaggle/working/TypePro")
        if not REPO_DIR.exists():
            run(["git", "clone", "--branch", BRANCH, "--single-branch", REPOSITORY, REPO_DIR])
        PIPELINE_DIR = REPO_DIR / "codet5p_type_retrieval"
        """),
        markdown("## Download, locate, and validate the completed shard output"),
        code("""
        source_owner, source_slug, source_version = SOURCE_KERNEL.split("/")
        source_handle = f"{source_owner}/{source_slug}/{source_version}"
        DOWNLOAD_ROOT = Path(
            f"/kaggle/working/recover_source_{SHARD_INDEX:02d}_v{source_version}"
        )
        print("Downloading exact saved output inside Kaggle:", source_handle)
        DOWNLOAD_ROOT.mkdir(parents=True, exist_ok=True)
        run([
            "kaggle", "kernels", "output", source_handle,
            "-p", DOWNLOAD_ROOT, "--force",
        ])
        INPUT_ROOT = DOWNLOAD_ROOT
        if not INPUT_ROOT.exists():
            raise RuntimeError(f"Downloaded output path does not exist: {INPUT_ROOT}")
        EXTRACT_ROOT = Path(f"/kaggle/working/recover_extract_{SHARD_INDEX:02d}")
        expected_archive = f"typepro_build_shard_{SHARD_INDEX:02d}.zip"
        archives = sorted(INPUT_ROOT.rglob(expected_archive))
        for position, archive in enumerate(archives):
            target = EXTRACT_ROOT / f"archive_{position:02d}"
            target.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(archive) as bundle:
                for member in bundle.infolist():
                    relative = PurePosixPath(member.filename)
                    if relative.is_absolute() or ".." in relative.parts:
                        raise RuntimeError(
                            f"Unsafe path in saved shard archive: {member.filename!r}"
                        )
                bundle.extractall(target)

        marker_paths = sorted(INPUT_ROOT.rglob("shard_manifest.json"))
        marker_paths.extend(sorted(EXTRACT_ROOT.rglob("shard_manifest.json")))
        candidates = []
        errors = []
        for marker_path in marker_paths:
            try:
                marker = json.loads(marker_path.read_text(encoding="utf-8"))
                if (
                    marker.get("shard_index") == SHARD_INDEX
                    and marker.get("shard_count") == SHARD_COUNT
                    and marker.get("missing_projects") == []
                    and isinstance(marker.get("selected_projects"), int)
                    and marker["selected_projects"] > 0
                    and marker.get("attempted_projects") == marker["selected_projects"]
                ):
                    candidates.append(marker_path.parent)
            except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
                errors.append(f"{marker_path}: {exc}")
        unique_candidates = sorted({path.resolve() for path in candidates})
        if not unique_candidates:
            raise RuntimeError(
                f"No completed shard {SHARD_INDEX:02d}/{SHARD_COUNT} in attached "
                f"output {source_handle}; archives={archives}, errors={errors}"
            )
        WORK_DIR = unique_candidates[0]
        print({
            "recovered_work_dir": str(WORK_DIR),
            "candidate_count": len(unique_candidates),
            "saved_archives": [str(path) for path in archives],
        })
        """),
        markdown("## Repackage and publish without rebuilding"),
        code("""
        PUBLISH_DIR = Path(f"/kaggle/working/recover_publish_{SHARD_INDEX:02d}")
        dataset_id = f"{EXPECTED_DATASET_OWNER}/typepro-build-shard-{SHARD_INDEX:02d}"
        publish_command = [
            sys.executable, "-u", PIPELINE_DIR / "publish_shard.py",
            "--work-dir", WORK_DIR,
            "--payload-dir", PUBLISH_DIR,
            "--dataset-id", dataset_id,
            "--title", f"TypePro Python shard {SHARD_INDEX:02d} of {SHARD_COUNT}",
            "--message", f"Recover completed shard {SHARD_INDEX:02d} from {SOURCE_KERNEL}",
            "--expected-shard-index", SHARD_INDEX,
            "--expected-shard-count", SHARD_COUNT,
        ]
        if PUBLISH_PUBLIC:
            publish_command.append("--public")
        run(publish_command)
        print({"recovered": True, "dataset_id": dataset_id})
        """),
    ])


def merge_notebook(
    count: int,
    repository: str,
    branch: str,
    *,
    expected_dataset_owner: str,
    shard_accounts: list[dict],
    merge_datasets: list[dict] | None = None,
) -> dict:
    if len(shard_accounts) != 2:
        raise ValueError("Merge notebook requires exactly two shard accounts")
    shard_source_config = []
    for position, item in enumerate(shard_accounts):
        owner = item["dataset_owner"]
        shards = list(item["assigned_shards"])
        if len(shards) != 5:
            raise ValueError(f"Merge source {owner!r} must contain five shards")
        shard_source_config.append({
            "label": f"runner_{chr(ord('a') + position)}",
            "secret_prefix": f"TYPEPRO_RUNNER_{chr(ord('A') + position)}",
            "owner": owner,
            "shards": shards,
            "public_dataset": bool(item["public_dataset"]),
        })
    if sorted(index for source in shard_source_config for index in source["shards"]) != list(range(count)):
        raise ValueError("Merge shard sources must cover every shard exactly once")
    if expected_dataset_owner.casefold() not in {
        source["owner"].casefold() for source in shard_source_config
    }:
        raise ValueError("Final Dataset owner must be one of the shard owners")
    for source in shard_source_config:
        should_be_public = source["owner"].casefold() != expected_dataset_owner.casefold()
        if source["public_dataset"] != should_be_public:
            raise ValueError(
                "Only the non-final account's shard Datasets must be public for merge"
            )
    merge_datasets = validate_merge_datasets(
        merge_datasets or canonical_merge_datasets(shard_accounts),
        count,
        expected_dataset_owner,
    )
    return notebook([
        markdown(f"""
        # Merge {count} TypePro shards and publish the final dataset

        Settings: **Internet ON**, accelerator **None/CPU**. Run under
        `{expected_dataset_owner}` so the automatic host identity can publish
        the final Dataset. Optional `TYPEPRO_FINAL_USERNAME/KEY` Secrets may
        override it. Shards owned by the final account remain private; shards
        owned by the second account are public so they can be attached as
        notebook inputs. Run only after all `{count}` shard Datasets complete.
        """),
        code(f"""
        SHARD_COUNT = {count}
        REPOSITORY = {repository!r}
        BRANCH = {branch!r}
        EXPECTED_DATASET_OWNER = {expected_dataset_owner!r}
        SHARD_SOURCE_CONFIG = {shard_source_config!r}
        MERGE_DATASETS = {merge_datasets!r}
        FINAL_DATASET_SLUG = "typepro-python-generative"
        SEED = 13
        # Must match the shard rerun: built-ins kept and returns included.
        INCLUDE_BUILTINS = True
        INCLUDE_RETURNS = True

        import json
        import os
        import shutil
        import subprocess
        import sys
        import zipfile
        from pathlib import Path
        from kaggle_secrets import UserSecretsClient

        secrets = UserSecretsClient()

        def optional_secret(name):
            try:
                value = secrets.get_secret(name)
            except Exception:
                return None
            value = value.strip() if value else ""
            return value or None

        final_username = optional_secret("TYPEPRO_FINAL_USERNAME")
        final_key = optional_secret("TYPEPRO_FINAL_KEY")
        if bool(final_username) != bool(final_key):
            raise RuntimeError(
                "TYPEPRO_FINAL_USERNAME and TYPEPRO_FINAL_KEY must both be present"
            )
        use_explicit_credential = bool(final_username and final_key)
        if not use_explicit_credential:
            final_username = EXPECTED_DATASET_OWNER
        if final_username.casefold() != EXPECTED_DATASET_OWNER.casefold():
            raise RuntimeError(
                f"Final credential belongs to {{final_username!r}}, expected "
                f"{{EXPECTED_DATASET_OWNER!r}}"
            )
        SHARD_SOURCES = SHARD_SOURCE_CONFIG
        FINAL_SOURCE = {{
            "label": "final_owner",
            "owner": EXPECTED_DATASET_OWNER,
            "username": final_username,
            "key": final_key,
        }}
        # The publisher validates Dataset ownership using KAGGLE_USERNAME.
        # This is safe to set for host-token authentication: it contains only
        # the public username and does not replace Kaggle's access token.
        os.environ["KAGGLE_USERNAME"] = final_username
        AUTH_ROOT = Path("/kaggle/working/typepro_merge_auth")
        AUTH_ROOT.mkdir(parents=True, exist_ok=True)

        def use_credential(source):
            if not use_explicit_credential:
                return
            auth_config_dir = AUTH_ROOT / source["label"]
            auth_config_dir.mkdir(parents=True, exist_ok=True)
            os.environ["KAGGLE_CONFIG_DIR"] = str(auth_config_dir)
            os.environ["KAGGLE_USERNAME"] = source["username"]
            os.environ["KAGGLE_KEY"] = source["key"]
            os.environ.pop("KAGGLE_API_TOKEN", None)

        os.environ["PYTHONUNBUFFERED"] = "1"
        print({{
            "shard_sources": [
                {{"owner": source["owner"], "shards": source["shards"]}}
                for source in SHARD_SOURCES
            ],
            "merge_datasets": [item["dataset_id"] for item in MERGE_DATASETS],
            "final_dataset_owner": EXPECTED_DATASET_OWNER,
            "authentication_source": (
                "explicit Kaggle Secret"
                if use_explicit_credential
                else "Kaggle notebook host"
            ),
            "credentials_printed": False,
        }})

        REPO_DIR = Path("/kaggle/working/TypePro")
        INPUT_ROOT = Path("/kaggle/input")
        EXTRACTED_INPUT_ROOT = Path("/kaggle/working/extracted_shard_inputs")
        MERGED_BUILD = Path("/kaggle/working/typepro_build")
        FINAL_DIR = Path("/kaggle/working/typepro_python_generative")

        def run(command, cwd=None):
            print("+", " ".join(map(str, command)), flush=True)
            subprocess.run([str(value) for value in command], cwd=cwd, check=True)
        """),
        markdown("## Clone code and install dependencies"),
        code("""
        if not REPO_DIR.exists():
            run(["git", "clone", "--branch", BRANCH, "--single-branch", REPOSITORY, REPO_DIR])
        PIPELINE_DIR = REPO_DIR / "codet5p_type_retrieval"
        run([sys.executable, "-m", "pip", "install", "-q", "-U", "-r", PIPELINE_DIR / "requirements-build.txt"])
        if use_explicit_credential:
            run([sys.executable, "-m", "pip", "install", "-q", "--force-reinstall", "kaggle==1.7.4.2"])
        else:
            run([sys.executable, "-m", "pip", "install", "-q", "-U", "kaggle"])

        identity_code = "\\n".join([
            "import json",
            "import kaggle",
            "values = getattr(kaggle.api, 'config_values', {})",
            "print('TYPEPRO_KAGGLE_IDENTITY=' + json.dumps({",
            "    'username': values.get('username'),",
            "    'auth_method': values.get('auth_method') or 'LEGACY_API_KEY',",
            "}))",
        ])
        identity_result = subprocess.run(
            [sys.executable, "-c", identity_code],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        identity_prefix = "TYPEPRO_KAGGLE_IDENTITY="
        identity_line = next(
            (
                line for line in (identity_result.stdout or "").splitlines()
                if line.startswith(identity_prefix)
            ),
            None,
        )
        if identity_result.returncode or identity_line is None:
            raise RuntimeError(
                f"Kaggle final-owner authentication failed: {identity_result.stdout}"
            )
        identity = json.loads(identity_line[len(identity_prefix):])
        authenticated_username = (identity.get("username") or "").strip()
        if authenticated_username.casefold() != EXPECTED_DATASET_OWNER.casefold():
            raise RuntimeError(
                f"Kaggle authenticated as {authenticated_username!r}, expected "
                f"final owner {EXPECTED_DATASET_OWNER!r}"
            )
        print({
            "authenticated_final_owner": authenticated_username,
            "authentication_method": identity.get("auth_method"),
        })
        """),
        markdown("## Validate all attached shard Dataset inputs"),
        code("""
        EXTRACTED_INPUT_ROOT.mkdir(parents=True, exist_ok=True)
        attached_builds = {}

        def register_manifest(marker_path):
            marker = json.loads(marker_path.read_text(encoding="utf-8"))
            coordinates = (marker.get("shard_index"), marker.get("shard_count"))
            attached_builds.setdefault(coordinates, []).append(
                (marker_path.parent, marker)
            )

        # Kaggle may normalize or suffix mounted directory names. Resolve each
        # input by its validated manifest coordinates instead of guessing a
        # /kaggle/input/<dataset-slug> path.
        for marker_path in INPUT_ROOT.rglob("shard_manifest.json"):
            register_manifest(marker_path)

        for archive_number, archive in enumerate(
            INPUT_ROOT.rglob("typepro_build_shard_*.zip")
        ):
            if list(archive.parent.rglob("shard_manifest.json")):
                continue
            target = EXTRACTED_INPUT_ROOT / f"archive_{archive_number:02d}"
            target.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(archive) as bundle:
                bundle.extractall(target)
            extracted_markers = list(target.rglob("shard_manifest.json"))
            if len(extracted_markers) != 1:
                raise RuntimeError(
                    f"Cannot uniquely locate manifest in attached archive {archive}: "
                    f"{extracted_markers}"
                )
            register_manifest(extracted_markers[0])

        shard_builds = []
        for item in MERGE_DATASETS:
            dataset_id = item["dataset_id"]
            index = item["shard_index"]
            expected_count = item["shard_count"]
            candidates = attached_builds.get((index, expected_count), [])
            if len(candidates) != 1:
                raise RuntimeError(
                    f"{dataset_id}: expected one attached build for "
                    f"{index}/{expected_count}, found {candidates}; "
                    f"mounted={sorted(str(path) for path in INPUT_ROOT.iterdir())}"
                )
            build, marker = candidates[0]
            if (
                marker["missing_projects"]
                or marker.get("selected_projects", 0) <= 0
                or marker.get("attempted_projects") != marker.get("selected_projects")
            ):
                raise RuntimeError(f"Invalid/incomplete shard marker: {marker}")
            required = [
                build / "metadata" / "split_manifest.json",
                build / "raw_slices",
                build / "project_status",
                build / "project_kb",
            ]
            missing = [str(path) for path in required if not path.exists()]
            if missing:
                raise RuntimeError(f"{dataset_id}: missing merge inputs: {missing}")
            shard_builds.append(build)
            print(f"Validated {dataset_id}: {marker['attempted_projects']} projects")
        print("All shard build directories:", [str(path) for path in shard_builds])
        """),
        markdown("## Merge shard outputs"),
        code("""
        merge_script = PIPELINE_DIR / "merge_shards.py"
        run([
            sys.executable, "-u", merge_script,
            "--shard-build-dirs", *shard_builds,
            "--work-dir", MERGED_BUILD,
        ])
        """),
        markdown("## Finalize generative train/validation/test and retain project KBs"),
        code("""
        prepare = PIPELINE_DIR / "prepare_dataset.py"
        finalize_flags = []
        if INCLUDE_BUILTINS:
            finalize_flags.append("--include-builtins")
        if INCLUDE_RETURNS:
            finalize_flags.append("--include-returns")
        run([
            sys.executable, "-u", prepare,
            "--stage", "finalize",
            "--typepro-root", REPO_DIR,
            "--work-dir", MERGED_BUILD,
            "--output-dir", FINAL_DIR,
            "--split-profile", "paper_project",
            "--test-projects", 100,
            "--validation-project-ratio", 0.10,
            "--seed", SEED,
            "--preview-samples", 2,
            "--preview-max-chars", 1600,
            "--log-every", 10000,
            *finalize_flags,
        ])
        run([sys.executable, PIPELINE_DIR / "verify_dataset.py", "--data-dir", FINAL_DIR])
        # Finalize has consumed the merged raw slices and KBs; drop the
        # transient build so publishing has room on the Kaggle working disk.
        shutil.rmtree(MERGED_BUILD, ignore_errors=True)
        """),
        markdown("## Display exact counts and examples"),
        code("""
        manifest = json.loads((FINAL_DIR / "manifest.json").read_text(encoding="utf-8"))
        stats = json.loads((FINAL_DIR / "preprocess_stats.json").read_text(encoding="utf-8"))
        print(json.dumps({
            "output": manifest["output"],
            "prepared_counts": manifest["split"]["prepared_counts"],
            "prepared_projects": manifest["split"]["prepared_projects"],
            "preprocess_stats": stats,
            "project_knowledge_bases": manifest["projects"]["knowledge_bases"],
        }, indent=2, ensure_ascii=False))
        for split in ("train", "validation", "test"):
            print(f"\\n===== {split.upper()} SAMPLES =====")
            with (FINAL_DIR / f"{split}.jsonl").open(encoding="utf-8") as handle:
                for _, line in zip(range(2), handle):
                    print(json.dumps(json.loads(line), indent=2, ensure_ascii=False)[:3000])
        """),
        markdown("## Publish final private Kaggle Dataset"),
        code("""
        use_credential(FINAL_SOURCE)
        final_id = f"{FINAL_SOURCE['owner']}/{FINAL_DATASET_SLUG}"
        run([
            sys.executable, PIPELINE_DIR / "publish_kaggle.py",
            "--data-dir", FINAL_DIR,
            "--dataset-id", final_id,
            "--title", "TypePro Python Generative Project-KB Data",
            "--message", f"Merge {len(MERGE_DATASETS)} verified partitions covering {SHARD_COUNT} shards",
        ])
        completion = {
            "dataset_id": final_id,
            "shard_count": SHARD_COUNT,
            "source_datasets": [item["dataset_id"] for item in MERGE_DATASETS],
            "output": manifest["output"],
        }
        (FINAL_DIR / "MERGE_COMPLETE.json").write_text(
            json.dumps(completion, indent=2), encoding="utf-8"
        )
        print(json.dumps(completion, indent=2))
        """),
    ])


def train_notebook(repository: str, branch: str) -> dict:
    return notebook([
        markdown("""
        # Fine-tune CodeT5+ and infer on the TypePro test split

        Settings: **Internet ON**, accelerator **GPU**. Attach the final private
        dataset `typepro-python-generative` using **Add Input**.
        """),
        code(f"""
        REPOSITORY = {repository!r}
        BRANCH = {branch!r}
        MODEL_NAME = "Salesforce/codet5p-220m-py"
        INPUT_LENGTH = 768
        LABEL_LENGTH = 64
        EPOCHS = 3

        import json
        import subprocess
        import sys
        from pathlib import Path

        REPO_DIR = Path("/kaggle/working/TypePro")
        OUTPUT_DIR = Path("/kaggle/working/codet5p-typepro-python")

        def run(command, cwd=None):
            print("+", " ".join(map(str, command)), flush=True)
            subprocess.run([str(value) for value in command], cwd=cwd, check=True)

        if not REPO_DIR.exists():
            run(["git", "clone", "--branch", BRANCH, "--single-branch", REPOSITORY, REPO_DIR])
        PIPELINE_DIR = REPO_DIR / "codet5p_type_retrieval"
        run([sys.executable, "-m", "pip", "install", "-q", "-r", PIPELINE_DIR / "requirements.txt"])
        """),
        markdown("## Locate and verify the attached processed dataset"),
        code("""
        candidates = []
        for path in Path("/kaggle/input").rglob("manifest.json"):
            try:
                value = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            if value.get("schema_version") == "typepro-codet5p-generative-project-kb-v2":
                candidates.append(path.parent)
        if len(candidates) != 1:
            raise RuntimeError(f"Expected exactly one TypePro processed dataset, found {candidates}")
        DATA_DIR = candidates[0]
        print("Using dataset:", DATA_DIR)
        run([sys.executable, PIPELINE_DIR / "verify_dataset.py", "--data-dir", DATA_DIR])
        """),
        markdown("## Measure token lengths before training"),
        code("""
        from transformers import AutoTokenizer

        tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

        def empty_token_stats(limit):
            return {
                "samples": 0,
                "total_tokens": 0,
                "min_tokens": None,
                "max_tokens": 0,
                "over_limit": 0,
                "configured_limit": limit,
            }

        def update_token_stats(stats, lengths):
            for length in lengths:
                stats["samples"] += 1
                stats["total_tokens"] += length
                stats["min_tokens"] = (
                    length if stats["min_tokens"] is None
                    else min(stats["min_tokens"], length)
                )
                stats["max_tokens"] = max(stats["max_tokens"], length)
                stats["over_limit"] += int(length > stats["configured_limit"])

        def finalized_token_stats(stats):
            count = stats["samples"]
            return {
                "samples": count,
                "average_tokens": round(stats["total_tokens"] / count, 2) if count else 0.0,
                "min_tokens": stats["min_tokens"] or 0,
                "max_tokens": stats["max_tokens"],
                "configured_limit": stats["configured_limit"],
                "over_limit": stats["over_limit"],
                "over_limit_percentage": (
                    round(100.0 * stats["over_limit"] / count, 2) if count else 0.0
                ),
            }

        def measure_split(path, batch_size=256):
            input_stats = empty_token_stats(INPUT_LENGTH)
            label_stats = empty_token_stats(LABEL_LENGTH)
            batch = []

            def measure_batch(rows):
                if not rows:
                    return
                input_ids = tokenizer(
                    [row["input"] for row in rows],
                    add_special_tokens=True,
                    truncation=False,
                )["input_ids"]
                label_ids = tokenizer(
                    text_target=[row["label"] for row in rows],
                    add_special_tokens=True,
                    truncation=False,
                )["input_ids"]
                update_token_stats(input_stats, [len(ids) for ids in input_ids])
                update_token_stats(label_stats, [len(ids) for ids in label_ids])

            with path.open(encoding="utf-8") as handle:
                for line in handle:
                    if not line.strip():
                        continue
                    batch.append(json.loads(line))
                    if len(batch) >= batch_size:
                        measure_batch(batch)
                        batch.clear()
                measure_batch(batch)
            return {"input": input_stats, "label": label_stats}

        raw_token_stats = {}
        overall = {
            "input": empty_token_stats(INPUT_LENGTH),
            "label": empty_token_stats(LABEL_LENGTH),
        }
        for split in ("train", "validation", "test"):
            raw_token_stats[split] = measure_split(DATA_DIR / f"{split}.jsonl")
            for field in ("input", "label"):
                current = raw_token_stats[split][field]
                combined = overall[field]
                combined["samples"] += current["samples"]
                combined["total_tokens"] += current["total_tokens"]
                combined["max_tokens"] = max(combined["max_tokens"], current["max_tokens"])
                if current["min_tokens"] is not None:
                    combined["min_tokens"] = (
                        current["min_tokens"] if combined["min_tokens"] is None
                        else min(combined["min_tokens"], current["min_tokens"])
                    )
                combined["over_limit"] += current["over_limit"]

        token_stats = {
            split: {
                field: finalized_token_stats(values)
                for field, values in split_values.items()
            }
            for split, split_values in raw_token_stats.items()
        }
        token_stats["overall"] = {
            field: finalized_token_stats(values)
            for field, values in overall.items()
        }
        print("===== TOKEN LENGTH STATISTICS (NO TRUNCATION) =====")
        print(json.dumps(token_stats, indent=2, ensure_ascii=False))
        """),
        markdown("## Generative sequence-to-sequence fine-tuning"),
        code("""
        run([
            sys.executable, "-u", PIPELINE_DIR / "train_generative.py",
            "--data-dir", DATA_DIR,
            "--output-dir", OUTPUT_DIR,
            "--model-name", MODEL_NAME,
            "--input-length", INPUT_LENGTH,
            "--label-length", LABEL_LENGTH,
            "--batch-size", 2,
            "--gradient-accumulation-steps", 8,
            "--epochs", EPOCHS,
            "--learning-rate", "2e-5",
            "--mixed-precision", "fp16",
            "--gradient-checkpointing",
            "--seed", 13,
        ])
        """),
        markdown("## Batched inference and test metrics"),
        code("""
        predictions = Path("/kaggle/working/test_predictions.jsonl")
        run([
            sys.executable, "-u", PIPELINE_DIR / "infer_generative.py",
            "--checkpoint", OUTPUT_DIR / "best",
            "--input", DATA_DIR / "test.jsonl",
            "--output", predictions,
            "--input-length", INPUT_LENGTH,
            "--label-length", LABEL_LENGTH,
            "--batch-size", 4,
        ])
        print("Predictions:", predictions)
        """),
    ], gpu=True)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--shards", type=int, default=10)
    parser.add_argument("--repository", default="https://github.com/duyvu1105/TypePro.git")
    parser.add_argument("--branch", default="main")
    parser.add_argument(
        "--runner-accounts",
        nargs="+",
        default=["duyvu1105", "duymign"],
        help="Kaggle accounts that host one versioned shard notebook each",
    )
    parser.add_argument(
        "--dataset-owner",
        default="duyvu1105",
        help="Owner of the final Dataset and the private shard group",
    )
    args, unknown = parser.parse_known_args(argv)
    # Jupyter kernels launch Python with ``-f <connection-file>``. Those
    # arguments are unrelated to this generator when its source is pasted into
    # a cell or executed via %run.
    remaining = list(unknown)
    while "-f" in remaining:
        index = remaining.index("-f")
        if index + 1 >= len(remaining):
            parser.error("argument -f: expected the Jupyter connection file")
        del remaining[index : index + 2]
    if remaining:
        parser.error(f"unrecognized arguments: {' '.join(remaining)}")
    if args.shards <= 0:
        raise ValueError("shards must be positive")
    if len(args.runner_accounts) != 2:
        raise ValueError("This workflow requires exactly two runner accounts")
    if args.shards != 10:
        raise ValueError("The two-account workflow requires exactly 10 shards")
    if len(set(account.casefold() for account in args.runner_accounts)) != 2:
        raise ValueError("Runner account names must be distinct")
    if not OWNER_RE.fullmatch(args.dataset_owner):
        raise ValueError(f"Invalid Dataset owner: {args.dataset_owner!r}")

    ROOT.mkdir(parents=True, exist_ok=True)
    owner_test_path = ROOT / "00_test_dataset_owner.ipynb"
    owner_test_path.write_text(
        json.dumps(owner_test_notebook(), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )
    for pattern in (
        "[0-9][0-9]_typepro_shard_*.ipynb",
        "[0-9][0-9]_typepro_account_*_shards_*.ipynb",
        "[0-9][0-9]_merge_finalize.ipynb",
        "[0-9][0-9]_train_and_infer.ipynb",
    ):
        for stale in ROOT.glob(pattern):
            stale.unlink()
    generated = [owner_test_path.name]
    shard_groups = [list(range(0, 5)), list(range(5, 10))]
    shard_accounts = []
    shard_notebooks = []
    for account, shard_group in zip(
        args.runner_accounts, shard_groups, strict=True
    ):
        public_dataset = account.casefold() != args.dataset_owner.casefold()
        shard_accounts.append({
            "runner_account": account,
            "dataset_owner": account,
            "public_dataset": public_dataset,
            "assigned_shards": shard_group,
        })
        for shard_index in shard_group:
            path = ROOT / f"{shard_index + 1:02d}_typepro_shard_{shard_index:02d}.ipynb"
            path.write_text(
                json.dumps(
                    shard_notebook(
                        shard_index,
                        args.shards,
                        args.repository,
                        args.branch,
                        assigned_shards=[shard_index],
                        expected_dataset_owner=account,
                        public_dataset=public_dataset,
                    ),
                    ensure_ascii=False,
                    indent=1,
                ),
                encoding="utf-8",
            )
            generated.append(path.name)
            shard_notebooks.append({
                "shard_index": shard_index,
                "part_count": len(physical_partitions(shard_index)),
                "runner_account": account,
                "dataset_owner": account,
                "public_dataset": public_dataset,
                "notebook": path.name,
                "kernel_slug": f"typepro-python-shard-{shard_index:02d}",
            })
    merge_datasets = canonical_merge_datasets(shard_accounts)
    merge_plan_path = ROOT / "shard_merge_plan.json"
    merge_plan_path.write_text(
        json.dumps({
            "schema_version": "typepro-shard-merge-plan-v3",
            "logical_shard_count": args.shards,
            "final_dataset_owner": args.dataset_owner,
            "datasets": merge_datasets,
        }, indent=2),
        encoding="utf-8",
    )
    generated.append(merge_plan_path.name)
    merge_path = ROOT / "11_merge_finalize.ipynb"
    merge_path.write_text(
        json.dumps(
            merge_notebook(
                args.shards,
                args.repository,
                args.branch,
                expected_dataset_owner=args.dataset_owner,
                shard_accounts=shard_accounts,
                merge_datasets=merge_datasets,
            ),
            ensure_ascii=False,
            indent=1,
        ),
        encoding="utf-8",
    )
    generated.append(merge_path.name)
    train_path = ROOT / "12_train_and_infer.ipynb"
    train_path.write_text(
        json.dumps(train_notebook(args.repository, args.branch), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )
    generated.append(train_path.name)
    plan_path = ROOT / "shard_account_plan.json"
    plan_path.write_text(
        json.dumps(
            {
                "schema_version": "typepro-shard-account-plan-v3",
                "final_dataset_owner": args.dataset_owner,
                "shard_count": args.shards,
                "shards": shard_notebooks,
                "merge_datasets": validate_merge_datasets(
                    merge_datasets,
                    args.shards,
                    args.dataset_owner,
                ),
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    generated.append(plan_path.name)
    print(json.dumps({"generated": generated}, indent=2))


if __name__ == "__main__":
    main()
