"""Generate upload-ready Kaggle notebooks for TypePro sharding and training.

The generated notebooks never contain a literal Kaggle credential. They read
KAGGLE_USERNAME and KAGGLE_KEY from Kaggle Secrets at runtime.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from textwrap import dedent
from uuid import uuid4


if "__file__" in globals():
    ROOT = Path(__file__).resolve().parent
elif Path("/kaggle/working").is_dir():
    # When this source is pasted into a Kaggle/Jupyter cell, ``__file__`` does
    # not exist. Keep generated notebooks in the session output directory so
    # they can be downloaded or saved as notebook output.
    ROOT = Path("/kaggle/working/kaggle_notebooks")
else:
    ROOT = Path.cwd() / "kaggle_notebooks"


def markdown(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": uuid4().hex[:8],
        "metadata": {},
        "source": dedent(source).strip() + "\n",
    }


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": uuid4().hex[:8],
        "metadata": {},
        "outputs": [],
        "source": dedent(source).strip() + "\n",
    }


def notebook(cells: list[dict], gpu: bool = False) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"},
            "kaggle": {
                "accelerator": "nvidiaTeslaT4" if gpu else "none",
                "isGpuEnabled": gpu,
                "isInternetEnabled": True,
                "language": "python",
                "sourceType": "notebook",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def owner_test_notebook() -> dict:
    return notebook([
        markdown("""
        # Verify cross-account Kaggle Dataset ownership

        This creates a tiny **private** Dataset to verify which account owns an
        upload. It is safe to run from a notebook hosted by account B while
        authenticating with an API token belonging to account A.

        Recommended Secrets:

        - `KAGGLE_API_TOKEN`: current API token generated by the target owner.
        - `KAGGLE_DATASET_OWNER`: public Kaggle username that must own the Dataset.

        Legacy `KAGGLE_USERNAME` plus `KAGGLE_KEY` is also supported. The `key`
        inside a legacy `kaggle.json` is **not** a `KAGGLE_API_TOKEN`; configure
        it using the legacy pair instead. Never put a token directly in a cell
        or print it. Revoke a temporarily shared token after this test.
        """),
        code("""
        # Kaggle CLI is installed after selecting the authentication mode below.
        """),
        markdown("## Load the target owner's credentials from Kaggle Secrets"),
        code("""
        import json
        import os
        import re
        import subprocess
        import sys
        from pathlib import Path
        from kaggle_secrets import UserSecretsClient

        secrets = UserSecretsClient()

        def optional_secret(name):
            try:
                value = secrets.get_secret(name)
            except Exception:
                return None
            value = value.strip() if value else ""
            return value or None

        api_token = optional_secret("KAGGLE_API_TOKEN")
        legacy_username = optional_secret("KAGGLE_USERNAME")
        legacy_key = optional_secret("KAGGLE_KEY")
        dataset_owner = optional_secret("KAGGLE_DATASET_OWNER") or legacy_username

        print({
            "KAGGLE_API_TOKEN_present": bool(api_token),
            "KAGGLE_USERNAME_present": bool(legacy_username),
            "KAGGLE_KEY_present": bool(legacy_key),
            "secret_values_printed": False,
        })
        if bool(legacy_username) != bool(legacy_key):
            raise RuntimeError(
                "Legacy authentication is incomplete: KAGGLE_USERNAME and "
                "KAGGLE_KEY must both be present"
            )

        if not dataset_owner:
            raise RuntimeError(
                "Add KAGGLE_DATASET_OWNER (recommended with KAGGLE_API_TOKEN) "
                "or KAGGLE_USERNAME to Kaggle Secrets"
            )
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{1,49}", dataset_owner):
            raise ValueError(f"Invalid KAGGLE_DATASET_OWNER: {dataset_owner!r}")

        # Isolate the CLI from any OAuth/config file belonging to the account
        # that hosts this notebook. Only the explicitly supplied Secret below
        # is allowed to authenticate this test.
        auth_config_dir = Path("/kaggle/working/typepro_owner_test_auth")
        auth_config_dir.mkdir(parents=True, exist_ok=True)
        os.environ["KAGGLE_CONFIG_DIR"] = str(auth_config_dir)

        # A complete legacy pair is explicit and takes precedence. This is
        # important in a cross-account Kaggle notebook because the hosting
        # account may also expose its own access token/OAuth credentials.
        if legacy_username and legacy_key:
            if dataset_owner.casefold() != legacy_username.casefold():
                raise RuntimeError(
                    "With legacy credentials, KAGGLE_DATASET_OWNER must equal KAGGLE_USERNAME"
                )
            os.environ.pop("KAGGLE_API_TOKEN", None)
            os.environ["KAGGLE_USERNAME"] = legacy_username
            os.environ["KAGGLE_KEY"] = legacy_key
            auth_mode = "legacy KAGGLE_USERNAME/KAGGLE_KEY"
        elif api_token:
            # Explicitly prefer the supplied target-owner token over any
            # credentials inherited from the notebook-hosting account.
            os.environ["KAGGLE_API_TOKEN"] = api_token
            os.environ.pop("KAGGLE_USERNAME", None)
            os.environ.pop("KAGGLE_KEY", None)
            auth_mode = "KAGGLE_API_TOKEN"
        else:
            raise RuntimeError(
                "Add either KAGGLE_API_TOKEN, or both KAGGLE_USERNAME and KAGGLE_KEY"
            )

        if auth_mode == "legacy KAGGLE_USERNAME/KAGGLE_KEY":
            # Kaggle CLI >=1.8 can consume the notebook-hosting account's
            # automatically provided access token before checking the explicit
            # legacy pair. Version 1.7.4.2 predates that authentication path.
            subprocess.run(
                [
                    sys.executable, "-m", "pip", "install", "-q",
                    "--force-reinstall", "kaggle==1.7.4.2",
                ],
                check=True,
            )
        else:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "-q", "-U", "kaggle"],
                check=True,
            )

        # Import Kaggle in a fresh process. Importing authenticates immediately,
        # so this reveals both the effective account and whether the supplied
        # Secret was accepted instead of silently falling back to host OAuth.
        identity_code = "\\n".join([
            "import json",
            "import kaggle",
            "api = kaggle.api",
            'values = getattr(api, "config_values", {})',
            'username = values.get("username")',
            'method = values.get("auth_method") or "LEGACY_API_KEY"',
            'print("TYPEPRO_KAGGLE_IDENTITY=" + json.dumps({',
            '    "username": username,',
            '    "auth_method": method,',
            '}))',
        ])
        identity_result = subprocess.run(
            [sys.executable, "-c", identity_code],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        identity_prefix = "TYPEPRO_KAGGLE_IDENTITY="
        identity_line = next(
            (
                line for line in (identity_result.stdout or "").splitlines()
                if line.startswith(identity_prefix)
            ),
            None,
        )
        if identity_result.returncode or identity_line is None:
            raise RuntimeError(
                "Kaggle authentication preflight failed. If you copied the key from "
                "kaggle.json, use KAGGLE_USERNAME + KAGGLE_KEY instead of "
                f"KAGGLE_API_TOKEN. CLI output: {identity_result.stdout}"
            )
        identity = json.loads(identity_line[len(identity_prefix):])
        authenticated_username = (identity.get("username") or "").strip()
        authenticated_method = (identity.get("auth_method") or "").strip()
        expected_method = (
            "LEGACY_API_KEY"
            if auth_mode == "legacy KAGGLE_USERNAME/KAGGLE_KEY"
            else "ACCESS_TOKEN"
        )
        if authenticated_username.casefold() != dataset_owner.casefold():
            raise RuntimeError(
                f"Credential authenticated as {authenticated_username!r}, but the requested "
                f"Dataset owner is {dataset_owner!r}. Use a credential generated by "
                "the requested owner account."
            )
        if authenticated_method != expected_method:
            raise RuntimeError(
                f"The supplied {auth_mode} was not accepted; Kaggle CLI used "
                f"{authenticated_method!r} instead. If this is a key from kaggle.json, "
                "remove KAGGLE_API_TOKEN and set KAGGLE_USERNAME + KAGGLE_KEY."
            )

        print({
            "requested_dataset_owner": dataset_owner,
            "authentication_mode": auth_mode,
            "authenticated_username": authenticated_username,
            "authenticated_method": authenticated_method,
            "secrets_printed": False,
        })
        """),
        markdown("## Create and validate a tiny private Dataset"),
        code("""
        import json
        import subprocess
        import time
        import uuid
        from datetime import datetime, timezone
        from pathlib import Path

        def run_capture(command):
            print("+", " ".join(map(str, command)), flush=True)
            result = subprocess.run(
                [str(value) for value in command],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            )
            if result.stdout:
                print(result.stdout.rstrip(), flush=True)
            return result

        now = datetime.now(timezone.utc)
        suffix = f"{now:%Y%m%d-%H%M%S}-{uuid.uuid4().hex[:6]}"
        dataset_slug = f"typepro-owner-test-{suffix}"
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]{2,49}", dataset_slug):
            raise RuntimeError(f"Generated invalid Dataset slug: {dataset_slug}")
        dataset_id = f"{dataset_owner}/{dataset_slug}"
        title = f"TypePro owner test {now:%Y%m%d %H%M%S}"
        if not 6 <= len(title) <= 50:
            raise RuntimeError(f"Generated invalid Dataset title: {title!r}")

        payload_dir = Path("/kaggle/working/typepro_owner_test_payload")
        payload_dir.mkdir(parents=True, exist_ok=True)
        record = {
            "purpose": "Verify cross-account Kaggle Dataset ownership",
            "requested_owner": dataset_owner,
            "created_at": now.isoformat(),
            "dataset_id": dataset_id,
        }
        (payload_dir / "owner_test.json").write_text(
            json.dumps(record, indent=2), encoding="utf-8"
        )
        metadata = {
            "title": title,
            "id": dataset_id,
            "licenses": [{"name": "CC-BY-4.0"}],
        }
        metadata_path = payload_dir / "dataset-metadata.json"
        metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        if json.loads(metadata_path.read_text(encoding="utf-8")) != metadata:
            raise RuntimeError("dataset-metadata.json verification failed")

        version_result = run_capture(["kaggle", "--version"])
        if version_result.returncode:
            raise RuntimeError("Kaggle CLI is unavailable")
        create_result = run_capture([
            "kaggle", "datasets", "create",
            "-p", payload_dir,
            "--dir-mode", "skip",
        ])
        create_text = create_result.stdout or ""
        create_lower = create_text.casefold()
        create_succeeded = (
            "dataset is being created" in create_lower
            and "dataset creation error:" not in create_lower
        )
        # Kaggle CLI 2.2.4 prints a server-side Dataset creation error but can
        # still exit with code 0. Never poll a slug that was not registered.
        if create_result.returncode or not create_succeeded:
            raise RuntimeError(
                f"Dataset registration failed for {dataset_id}. Kaggle may have uploaded "
                "the blob without creating the Dataset. Verify Dataset write permission "
                f"for the authenticated owner. CLI output: {create_text}"
            )

        # The legacy status endpoint can return 403 even immediately after a
        # successful create. Listing the uploaded file is a stronger end-to-end
        # verification and works with legacy credentials.
        deadline = time.monotonic() + 600
        final_status = None
        last_files_output = ""
        while time.monotonic() < deadline:
            files_result = run_capture([
                "kaggle", "datasets", "files", dataset_id, "--page-size", "10"
            ])
            last_files_output = files_result.stdout or ""
            if files_result.returncode == 0 and "owner_test.json" in last_files_output:
                final_status = "ready; owner_test.json is listable"
                break
            files_text = last_files_output.casefold()
            transient = any(
                marker in files_text
                for marker in ("403", "404", "forbidden", "not found", "could not find")
            )
            if files_result.returncode and not transient:
                raise RuntimeError(f"Cannot list Dataset files: {last_files_output}")
            print("Dataset files are not ready yet; checking again in 10 seconds", flush=True)
            time.sleep(10)
        if final_status is None:
            raise TimeoutError(
                f"Dataset file did not become listable within 600 seconds: {dataset_id}; "
                f"last output: {last_files_output}"
            )

        dataset_url = f"https://www.kaggle.com/datasets/{dataset_id}"
        print(json.dumps({
            "verified": True,
            "owner": dataset_owner,
            "dataset_id": dataset_id,
            "dataset_url": dataset_url,
            "status": final_status,
        }, indent=2, ensure_ascii=False))
        """),
        markdown("""
        A result with `"verified": true` proves that Kaggle accepted the
        requested `owner/slug`, finished processing it, and exposes the uploaded
        test file. Open `dataset_url` while signed into the target owner account.
        """),
    ])


def shard_notebook(index: int, count: int, repository: str, branch: str) -> dict:
    title = f"TypePro Python dataset shard {index:02d}/{count - 1:02d}"
    return notebook([
        markdown(f"""
        # {title}

        Settings required: **Internet ON**, accelerator **None/CPU**. Add account
        secrets `KAGGLE_USERNAME` and `KAGGLE_KEY`. This notebook processes shard
        `{index}` of `{count}` and publishes a private dataset named
        `typepro-build-shard-{index:02d}`.
        """),
        code(f"""
        SHARD_INDEX = {index}
        SHARD_COUNT = {count}
        REPOSITORY = {repository!r}
        BRANCH = {branch!r}
        SEED = 13
        TEST_PROJECTS = 100
        VALIDATION_PROJECT_RATIO = 0.10
        SLICE_LOG_EVERY = 50

        from pathlib import Path

        REPO_DIR = Path("/kaggle/working/TypePro")
        WORK_DIR = Path(f"/kaggle/working/typepro_build_shard_{{SHARD_INDEX:02d}}")
        PUBLISH_DIR = Path(f"/kaggle/working/publish_shard_{{SHARD_INDEX:02d}}")
        print({{
            "shard_index": SHARD_INDEX,
            "shard_count": SHARD_COUNT,
            "work_dir": str(WORK_DIR),
        }})
        """),
        markdown("""
        ## Authenticate safely

        Values are read from Kaggle Secrets and are never printed.
        """),
        code("""
        import os
        from kaggle_secrets import UserSecretsClient

        secrets = UserSecretsClient()
        kaggle_username = secrets.get_secret("KAGGLE_USERNAME").strip()
        kaggle_key = secrets.get_secret("KAGGLE_KEY").strip()
        if not kaggle_username or not kaggle_key:
            raise RuntimeError("KAGGLE_USERNAME and KAGGLE_KEY must not be empty")
        os.environ["KAGGLE_USERNAME"] = kaggle_username
        os.environ["KAGGLE_KEY"] = kaggle_key
        os.environ.pop("KAGGLE_API_TOKEN", None)
        os.environ["PYTHONUNBUFFERED"] = "1"
        print("Datasets will be owned by:", kaggle_username)
        """),
        markdown("## Clone TypePro and install builder dependencies"),
        code("""
        import shutil
        import subprocess
        import sys

        def run(command, cwd=None):
            print("+", " ".join(map(str, command)), flush=True)
            subprocess.run([str(value) for value in command], cwd=cwd, check=True)

        if not REPO_DIR.exists():
            run(["git", "clone", "--branch", BRANCH, "--single-branch", REPOSITORY, REPO_DIR])
        else:
            print("Using existing repository:", REPO_DIR)

        PIPELINE_DIR = REPO_DIR / "codet5p_type_retrieval"
        run([sys.executable, "-m", "pip", "install", "-q", "-U", "-r", PIPELINE_DIR / "requirements-build.txt"])
        # Force legacy-key-only authentication. Newer Kaggle CLI releases may
        # prefer the notebook host account's automatic access token.
        run([sys.executable, "-m", "pip", "install", "-q", "--force-reinstall", "kaggle==1.7.4.2"])
        """),
        markdown("""
        ## Optional automatic resume

        If the private shard dataset already exists, its archive is downloaded
        and restored before slicing. A missing dataset simply means this is the
        first run.
        """),
        code("""
        import json
        import zipfile

        dataset_id = f"{os.environ['KAGGLE_USERNAME']}/typepro-build-shard-{SHARD_INDEX:02d}"
        resume_dir = Path(f"/kaggle/working/resume_shard_{SHARD_INDEX:02d}")
        resume_dir.mkdir(parents=True, exist_ok=True)
        probe = subprocess.run(
            ["kaggle", "datasets", "files", dataset_id],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        has_work = (
            (WORK_DIR / "metadata" / "split_manifest.json").exists()
            or any((WORK_DIR / "raw_slices").glob("*.jsonl"))
            or any((WORK_DIR / "project_status").glob("*.json"))
        )
        if probe.returncode == 0 and not has_work:
            run(["kaggle", "datasets", "download", "-d", dataset_id, "-p", resume_dir, "--unzip"])
            markers = list(resume_dir.rglob("shard_manifest.json"))
            if not markers:
                archives = list(resume_dir.rglob("typepro_build_shard_*.zip"))
                if len(archives) != 1:
                    raise RuntimeError(
                        f"Expected one shard directory or archive, found markers={markers}, archives={archives}"
                    )
                with zipfile.ZipFile(archives[0]) as bundle:
                    bundle.extractall(resume_dir)
                markers = list(resume_dir.rglob("shard_manifest.json"))
            if len(markers) != 1:
                raise RuntimeError(f"Cannot uniquely locate restored shard: {markers}")
            source_build = markers[0].parent
            restored_manifest = json.loads(markers[0].read_text(encoding="utf-8"))
            if (
                restored_manifest.get("shard_index") != SHARD_INDEX
                or restored_manifest.get("shard_count") != SHARD_COUNT
            ):
                print(
                    "Ignoring an incompatible previous shard Dataset; starting the new layout:",
                    restored_manifest,
                )
            else:
                shutil.copytree(source_build, WORK_DIR, dirs_exist_ok=True)
                print("Restored previous shard state:", WORK_DIR)
        else:
            print("Starting new shard or using current working state")
        """),
        markdown("## Download metadata and create the deterministic project split"),
        code("""
        prepare = PIPELINE_DIR / "prepare_dataset.py"
        common = [
            "--typepro-root", REPO_DIR,
            "--work-dir", WORK_DIR,
            "--split-profile", "paper_project",
            "--test-projects", TEST_PROJECTS,
            "--validation-project-ratio", VALIDATION_PROJECT_RATIO,
            "--seed", SEED,
            "--preview-samples", 1,
            "--preview-max-chars", 1200,
        ]
        run([sys.executable, "-u", prepare, "--stage", "metadata", *common])
        """),
        markdown("## Clone repositories and build interprocedural slices"),
        code("""
        run([
            sys.executable, "-u", prepare,
            "--stage", "slice",
            *common,
            "--shard-count", SHARD_COUNT,
            "--shard-index", SHARD_INDEX,
            "--slice-log-every", SLICE_LOG_EVERY,
            "--build-import-kb",
            "--download-missing-imports",
            "--kb-max-files-per-package", 3000,
        ])
        """),
        markdown("## Verify that this shard attempted every assigned project"),
        code("""
        import json
        sys.path.insert(0, str(PIPELINE_DIR))
        from prepare_dataset import project_from_row, read_json, stable_number

        projects = set()
        for split in ("train", "validation", "test"):
            for row in read_json(WORK_DIR / "metadata" / f"{split}.json"):
                projects.add(project_from_row(row))
        selected = {
            project for project in projects
            if stable_number(project, SEED + 4) % SHARD_COUNT == SHARD_INDEX
        }
        statuses = []
        for path in (WORK_DIR / "project_status").glob("*.json"):
            statuses.append(json.loads(path.read_text(encoding="utf-8")))
        attempted = {item.get("project") for item in statuses}
        missing = sorted(selected - attempted)
        summary = {
            "shard_index": SHARD_INDEX,
            "shard_count": SHARD_COUNT,
            "selected_projects": len(selected),
            "attempted_projects": len(selected & attempted),
            "successful_projects": sum(item.get("project") in selected and "error" not in item for item in statuses),
            "failed_projects": sum(item.get("project") in selected and "error" in item for item in statuses),
            "exported_slices": sum(int(item.get("exported", 0)) for item in statuses if item.get("project") in selected),
            "missing_projects": missing,
        }
        print(json.dumps(summary, indent=2, ensure_ascii=False))
        (WORK_DIR / "shard_manifest.json").write_text(
            json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        if missing:
            raise RuntimeError(f"Shard is incomplete: {len(missing)} projects missing")
        """),
        markdown("## Package and publish this shard as a private Kaggle Dataset"),
        code("""
        run([
            sys.executable, "-u", PIPELINE_DIR / "publish_shard.py",
            "--work-dir", WORK_DIR,
            "--payload-dir", PUBLISH_DIR,
            "--dataset-id", dataset_id,
            "--title", f"TypePro Python shard {SHARD_INDEX:02d} of {SHARD_COUNT}",
            "--message", f"Completed TypePro shard {SHARD_INDEX:02d} of {SHARD_COUNT}",
            "--expected-shard-index", SHARD_INDEX,
            "--expected-shard-count", SHARD_COUNT,
        ])
        """),
    ])


def merge_notebook(count: int, repository: str, branch: str) -> dict:
    return notebook([
        markdown(f"""
        # Merge {count} TypePro shards and publish the final dataset

        Settings: **Internet ON**, accelerator **None/CPU**. Add secrets
        `KAGGLE_USERNAME` and `KAGGLE_KEY`. Run only after all `{count}` private
        shard datasets have been published successfully.
        """),
        code(f"""
        SHARD_COUNT = {count}
        REPOSITORY = {repository!r}
        BRANCH = {branch!r}
        FINAL_DATASET_SLUG = "typepro-python-contrastive"
        SEED = 13

        import json
        import os
        import shutil
        import subprocess
        import sys
        import zipfile
        from pathlib import Path
        from kaggle_secrets import UserSecretsClient

        secrets = UserSecretsClient()
        kaggle_username = secrets.get_secret("KAGGLE_USERNAME").strip()
        kaggle_key = secrets.get_secret("KAGGLE_KEY").strip()
        if not kaggle_username or not kaggle_key:
            raise RuntimeError("KAGGLE_USERNAME and KAGGLE_KEY must not be empty")
        os.environ["KAGGLE_USERNAME"] = kaggle_username
        os.environ["KAGGLE_KEY"] = kaggle_key
        os.environ.pop("KAGGLE_API_TOKEN", None)
        os.environ["PYTHONUNBUFFERED"] = "1"
        print("Datasets will be read from and published to:", kaggle_username)

        REPO_DIR = Path("/kaggle/working/TypePro")
        DOWNLOAD_DIR = Path("/kaggle/working/downloaded_shards")
        MERGED_BUILD = Path("/kaggle/working/typepro_build")
        FINAL_DIR = Path("/kaggle/working/typepro_python_contrastive")

        def run(command, cwd=None):
            print("+", " ".join(map(str, command)), flush=True)
            subprocess.run([str(value) for value in command], cwd=cwd, check=True)
        """),
        markdown("## Clone code and install dependencies"),
        code("""
        if not REPO_DIR.exists():
            run(["git", "clone", "--branch", BRANCH, "--single-branch", REPOSITORY, REPO_DIR])
        PIPELINE_DIR = REPO_DIR / "codet5p_type_retrieval"
        run([sys.executable, "-m", "pip", "install", "-q", "-U", "-r", PIPELINE_DIR / "requirements-build.txt"])
        # Force legacy-key-only authentication for cross-account publishing.
        run([sys.executable, "-m", "pip", "install", "-q", "--force-reinstall", "kaggle==1.7.4.2"])
        """),
        markdown("## Download and extract every private shard dataset"),
        code("""
        DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)
        shard_builds = []
        for index in range(SHARD_COUNT):
            dataset_id = f"{os.environ['KAGGLE_USERNAME']}/typepro-build-shard-{index:02d}"
            target = DOWNLOAD_DIR / f"shard_{index:02d}"
            target.mkdir(parents=True, exist_ok=True)
            run(["kaggle", "datasets", "download", "-d", dataset_id, "-p", target, "--unzip"])
            marker_paths = list(target.rglob("shard_manifest.json"))
            if not marker_paths:
                # Older shard datasets may preserve the pre-packed ZIP, while
                # Kaggle expands newer uploads into a directory tree.
                archives = list(target.rglob("typepro_build_shard_*.zip"))
                if len(archives) != 1:
                    raise RuntimeError(
                        f"{dataset_id}: expected one build directory or archive, "
                        f"found markers={marker_paths}, archives={archives}"
                    )
                with zipfile.ZipFile(archives[0]) as bundle:
                    bundle.extractall(target)
                marker_paths = list(target.rglob("shard_manifest.json"))
            if len(marker_paths) != 1:
                raise RuntimeError(f"{dataset_id}: cannot uniquely locate shard build: {marker_paths}")
            build = marker_paths[0].parent
            marker = json.loads(marker_paths[0].read_text(encoding="utf-8"))
            if marker["shard_index"] != index or marker["shard_count"] != SHARD_COUNT or marker["missing_projects"]:
                raise RuntimeError(f"Invalid/incomplete shard marker: {marker}")
            required = [
                build / "metadata" / "split_manifest.json",
                build / "raw_slices",
                build / "project_status",
            ]
            missing = [str(path) for path in required if not path.exists()]
            if missing:
                raise RuntimeError(f"{dataset_id}: missing merge inputs: {missing}")
            shard_builds.append(build)
            print(f"Validated shard {index:02d}: {marker['attempted_projects']} projects")
        print("All shard build directories:", [str(path) for path in shard_builds])
        """),
        markdown("## Merge shard outputs"),
        code("""
        merge_script = PIPELINE_DIR / "merge_shards.py"
        run([
            sys.executable, "-u", merge_script,
            "--shard-build-dirs", *shard_builds,
            "--work-dir", MERGED_BUILD,
        ])
        """),
        markdown("## Finalize contrastive train/validation/test"),
        code("""
        prepare = PIPELINE_DIR / "prepare_dataset.py"
        run([
            sys.executable, "-u", prepare,
            "--stage", "finalize",
            "--typepro-root", REPO_DIR,
            "--work-dir", MERGED_BUILD,
            "--output-dir", FINAL_DIR,
            "--split-profile", "paper_project",
            "--test-projects", 100,
            "--validation-project-ratio", 0.10,
            "--max-negatives", 7,
            "--seed", SEED,
            "--preview-samples", 2,
            "--preview-max-chars", 1600,
            "--log-every", 10000,
        ])
        run([sys.executable, PIPELINE_DIR / "verify_dataset.py", "--data-dir", FINAL_DIR])
        """),
        markdown("## Display exact counts and examples"),
        code("""
        manifest = json.loads((FINAL_DIR / "manifest.json").read_text(encoding="utf-8"))
        stats = json.loads((FINAL_DIR / "preprocess_stats.json").read_text(encoding="utf-8"))
        recommendation_coverage = {}
        for split in ("train", "validation", "test"):
            found = stats.get(f"{split}_gold_recommended", 0)
            missing = stats.get(f"{split}_gold_not_recommended", 0)
            total = found + missing
            recommendation_coverage[split] = {
                "total_samples": total,
                "ground_truth_in_recommendation_types": found,
                "ground_truth_not_in_recommendation_types": missing,
                "percentage": round(100.0 * found / total, 2) if total else 0.0,
            }
        print(json.dumps({
            "output": manifest["output"],
            "prepared_counts": manifest["split"]["prepared_counts"],
            "prepared_projects": manifest["split"]["prepared_projects"],
            "preprocess_stats": stats,
            "recommendation_coverage": recommendation_coverage,
        }, indent=2, ensure_ascii=False))
        print("\n===== GROUND TRUTH IN RECOMMENDATION TYPES =====")
        for split, values in recommendation_coverage.items():
            print(
                f"{split}: {values['ground_truth_in_recommendation_types']:,}/"
                f"{values['total_samples']:,} samples ({values['percentage']:.2f}%)"
            )
        for split in ("train", "validation", "test"):
            print(f"\\n===== {split.upper()} SAMPLES =====")
            with (FINAL_DIR / f"{split}.jsonl").open(encoding="utf-8") as handle:
                for _, line in zip(range(2), handle):
                    print(json.dumps(json.loads(line), indent=2, ensure_ascii=False)[:3000])
        """),
        markdown("## Publish final private Kaggle Dataset"),
        code("""
        final_id = f"{os.environ['KAGGLE_USERNAME']}/{FINAL_DATASET_SLUG}"
        run([
            sys.executable, PIPELINE_DIR / "publish_kaggle.py",
            "--data-dir", FINAL_DIR,
            "--dataset-id", final_id,
            "--title", "TypePro Python Third-Party Contrastive Data",
            "--message", f"Merge {SHARD_COUNT} verified TypePro shards",
        ])
        completion = {
            "dataset_id": final_id,
            "shard_count": SHARD_COUNT,
            "output": manifest["output"],
        }
        (FINAL_DIR / "MERGE_COMPLETE.json").write_text(
            json.dumps(completion, indent=2), encoding="utf-8"
        )
        print(json.dumps(completion, indent=2))
        """),
    ])


def train_notebook(repository: str, branch: str) -> dict:
    return notebook([
        markdown("""
        # Fine-tune CodeT5+ and infer on the TypePro test split

        Settings: **Internet ON**, accelerator **GPU**. Attach the final private
        dataset `typepro-python-contrastive` using **Add Input**.
        """),
        code(f"""
        REPOSITORY = {repository!r}
        BRANCH = {branch!r}
        MODEL_NAME = "Salesforce/codet5p-220m-py"
        QUERY_LENGTH = 768
        CANDIDATE_LENGTH = 256
        EPOCHS = 3

        import json
        import subprocess
        import sys
        from pathlib import Path

        REPO_DIR = Path("/kaggle/working/TypePro")
        OUTPUT_DIR = Path("/kaggle/working/codet5p-typepro-python")

        def run(command, cwd=None):
            print("+", " ".join(map(str, command)), flush=True)
            subprocess.run([str(value) for value in command], cwd=cwd, check=True)

        if not REPO_DIR.exists():
            run(["git", "clone", "--branch", BRANCH, "--single-branch", REPOSITORY, REPO_DIR])
        PIPELINE_DIR = REPO_DIR / "codet5p_type_retrieval"
        run([sys.executable, "-m", "pip", "install", "-q", "-r", PIPELINE_DIR / "requirements.txt"])
        """),
        markdown("## Locate and verify the attached processed dataset"),
        code("""
        candidates = []
        for path in Path("/kaggle/input").rglob("manifest.json"):
            try:
                value = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            if value.get("schema_version", "").startswith("typepro-codet5p-contrastive"):
                candidates.append(path.parent)
        if len(candidates) != 1:
            raise RuntimeError(f"Expected exactly one TypePro processed dataset, found {candidates}")
        DATA_DIR = candidates[0]
        print("Using dataset:", DATA_DIR)
        run([sys.executable, PIPELINE_DIR / "verify_dataset.py", "--data-dir", DATA_DIR])
        """),
        markdown("## Contrastive fine-tuning"),
        code("""
        run([
            sys.executable, "-u", PIPELINE_DIR / "train.py",
            "--data-dir", DATA_DIR,
            "--output-dir", OUTPUT_DIR,
            "--model-name", MODEL_NAME,
            "--projection-dim", 256,
            "--query-length", QUERY_LENGTH,
            "--candidate-length", CANDIDATE_LENGTH,
            "--batch-size", 2,
            "--gradient-accumulation-steps", 8,
            "--epochs", EPOCHS,
            "--learning-rate", "2e-5",
            "--mixed-precision", "fp16",
            "--gradient-checkpointing",
            "--preview-samples", 2,
            "--preview-max-chars", 1600,
            "--seed", 13,
        ])
        """),
        markdown("## Batched inference and test metrics"),
        code("""
        predictions = Path("/kaggle/working/test_predictions.jsonl")
        run([
            sys.executable, "-u", PIPELINE_DIR / "infer.py",
            "--checkpoint", OUTPUT_DIR / "best",
            "--input", DATA_DIR / "test.jsonl",
            "--output", predictions,
            "--query-length", QUERY_LENGTH,
            "--candidate-length", CANDIDATE_LENGTH,
            "--batch-size", 4,
            "--top-k", 5,
            "--preview-samples", 3,
            "--log-every", 1000,
        ])
        print("Predictions:", predictions)
        """),
    ], gpu=True)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--shards", type=int, default=10)
    parser.add_argument("--repository", default="https://github.com/duyvu1105/TypePro.git")
    parser.add_argument("--branch", default="main")
    args, unknown = parser.parse_known_args(argv)
    # Jupyter kernels launch Python with ``-f <connection-file>``. Those
    # arguments are unrelated to this generator when its source is pasted into
    # a cell or executed via %run.
    remaining = list(unknown)
    while "-f" in remaining:
        index = remaining.index("-f")
        if index + 1 >= len(remaining):
            parser.error("argument -f: expected the Jupyter connection file")
        del remaining[index : index + 2]
    if remaining:
        parser.error(f"unrecognized arguments: {' '.join(remaining)}")
    if args.shards <= 0:
        raise ValueError("shards must be positive")

    ROOT.mkdir(parents=True, exist_ok=True)
    owner_test_path = ROOT / "00_test_dataset_owner.ipynb"
    owner_test_path.write_text(
        json.dumps(owner_test_notebook(), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )
    for pattern in ("[0-9][0-9]_typepro_shard_*.ipynb", "[0-9][0-9]_merge_finalize.ipynb", "[0-9][0-9]_train_and_infer.ipynb"):
        for stale in ROOT.glob(pattern):
            stale.unlink()
    generated = [owner_test_path.name]
    for index in range(args.shards):
        path = ROOT / f"{index + 1:02d}_typepro_shard_{index:02d}.ipynb"
        path.write_text(
            json.dumps(shard_notebook(index, args.shards, args.repository, args.branch), ensure_ascii=False, indent=1),
            encoding="utf-8",
        )
        generated.append(path.name)
    merge_path = ROOT / f"{args.shards + 1:02d}_merge_finalize.ipynb"
    merge_path.write_text(
        json.dumps(merge_notebook(args.shards, args.repository, args.branch), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )
    generated.append(merge_path.name)
    train_path = ROOT / f"{args.shards + 2:02d}_train_and_infer.ipynb"
    train_path.write_text(
        json.dumps(train_notebook(args.repository, args.branch), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )
    generated.append(train_path.name)
    print(json.dumps({"generated": generated}, indent=2))


if __name__ == "__main__":
    main()
